linters-settings:
    golint:
        min-confidence: 0.1
    goimports:
        local-prefixes: emperror.dev/emperror

linters:
    enable-all: true
    disable:
        # TODO: fixme
        - godox

        - funlen
        - wsl

service:
    golangci-lint-version: 1.21.x
